<?php

/**
 * ConstantesEstatisticaFuncao
 */
class ConstantesEstatisticaFuncao
{
	const FUNCAO_CRIAR_CAMPANHA = 'FUNCAO_CRIAR_CAMPANHA';
	const FUNCAO_CONTAGEM_CFDI = 'FUNCAO_CONTAGEM_CFDI';
	const FUNCAO_MAXIMO_CARTOES = 'FUNCAO_MAXIMO_CARTOES';
	const FUNCAO_CRIAR_PROMOCAO_PLANO = 'FUNCAO_CRIAR_PROMOCAO_PLANO';
	const FUNCAO_ADICIONAR_CARTOES_CAMPANHA = 'FUNCAO_ADICIONAR_CARTOES_CAMPANHA';

}
?>