/* query para extrair as FK do MySql Schema cfd */
mysql -h localhost -u cfd -p

connect cfd;

select concat('ALTER TABLE ',TABLE_NAME,' DROP FOREIGN KEY ', CONSTRAINT_NAME, ';')
from information_schema.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'cfd'
AND CONSTRAINT_NAME LIKE 'FK_%';

/* desabilita todas FKs para efetivar o DROP TABLE */
SET FOREIGN_KEY_CHECKS=0;

 ALTER TABLE campanha DROP FOREIGN KEY FK_CAMP_USUA;

 ALTER TABLE campanha_cashback DROP FOREIGN KEY FK_CACA_CAMP;

 ALTER TABLE campanha_cashback DROP FOREIGN KEY FK_CACA_USCA;

 ALTER TABLE campanha_cashback DROP FOREIGN KEY FK_CACA_USUA;

 ALTER TABLE campanha_cashback_cc DROP FOREIGN KEY FK_CACC_CACA;

 ALTER TABLE campanha_cashback_cc DROP FOREIGN KEY FK_CACC_CAMP;

 ALTER TABLE campanha_cashback_cc DROP FOREIGN KEY FK_CACC_CFDI;

 ALTER TABLE campanha_cashback_cc DROP FOREIGN KEY FK_CACC_USUA;

 ALTER TABLE campanha_cashback_cc DROP FOREIGN KEY FK_CACC_USUA_DONO;

 ALTER TABLE campanha_historico DROP FOREIGN KEY FK_CAHI_CAMP;

 ALTER TABLE campanha_qrcodes DROP FOREIGN KEY FK_CAQR_CAMP;

 ALTER TABLE campanha_qrcodes DROP FOREIGN KEY FK_CAQR_USUA;

 ALTER TABLE cartao DROP FOREIGN KEY FK_CART_QRCU;

 ALTER TABLE cfdi DROP FOREIGN KEY FK_CFDI_CAMP;

 ALTER TABLE cfdi DROP FOREIGN KEY FK_CFDI_USUA;

 ALTER TABLE cfdi DROP FOREIGN KEY FK_CFDI_USUA_GERADOR;

 ALTER TABLE plano_usuario DROP FOREIGN KEY FK_PLUS_PLAN;

 ALTER TABLE plano_usuario DROP FOREIGN KEY FK_PLUS_USUA;

 ALTER TABLE plano_usuario_fatura DROP FOREIGN KEY FK_PLUF_PLUS;

 ALTER TABLE qrcodes_curinga DROP FOREIGN KEY FK_QRCU_CAMP;

 ALTER TABLE qrcodes_curinga DROP FOREIGN KEY FK_QRCU_CART;

 ALTER TABLE qrcodes_curinga DROP FOREIGN KEY FK_QRCU_USUA;

 ALTER TABLE qrcodes_curinga DROP FOREIGN KEY FK_QRCU_USUA2;

 ALTER TABLE uf_cidade_item DROP FOREIGN KEY FK_CIDADE_UF_CIDADE_ITEM;

 ALTER TABLE uf_cidade_item DROP FOREIGN KEY FK_UF_UF_CIDADE_ITEM;

 ALTER TABLE usuario_autorizador DROP FOREIGN KEY FK_USAU_CAMP_ID;

 ALTER TABLE usuario_autorizador DROP FOREIGN KEY FK_USAU_USUA_ID;

 ALTER TABLE usuario_autorizador DROP FOREIGN KEY FK_USAU_USUA_ID_AUTORIZADOR;

 ALTER TABLE usuario_cashback DROP FOREIGN KEY FK_USCA_USUA;

 ALTER TABLE usuario_complemento DROP FOREIGN KEY FK_USCO_USUA;

 ALTER TABLE usuario_notificacao DROP FOREIGN KEY FK_USNO_USUA;

 ALTER TABLE usuario_publicidade DROP FOREIGN KEY FK_USPU_CAMP;

 ALTER TABLE usuario_tipo_empreendimento DROP FOREIGN KEY FK_USTE_TIEM;

 ALTER TABLE usuario_tipo_empreendimento DROP FOREIGN KEY FK_USTE_USUA;

 ALTER TABLE usuario_troca_senha_historico DROP FOREIGN KEY FK_UTSH_USUA;

DROP TABLE CARTAO_HISTORICO;
DROP TABLE CAMPANHA_HISTORICO;
DROP TABLE UF_CIDADE_ITEM;
DROP TABLE ESTATISTICA_FUNCAO;
DROP TABLE ESTATISTICA_FUNCAO_07D;
DROP TABLE ESTATISTICA_FUNCAO_14D;
DROP TABLE ESTATISTICA_FUNCAO_30D;
DROP TABLE USUARIO_PUBLICIDADE;
DROP TABLE CAMPANHA_QRCODES;
DROP TABLE QRCODES_CURINGA;
DROP TABLE CFDI;
DROP TABLE PLANO_USUARIO_FATURA;
DROP TABLE PLANO_USUARIO;
DROP TABLE CAMPANHA_CASHBACK_CC;
DROP TABLE CAMPANHA_CASHBACK;
DROP TABLE USUARIO_AVALIACAO;
DROP TABLE USUARIO_CASHBACK;
DROP TABLE USUARIO_TIPO_EMPREENDIMENTO;
DROP TABLE USUARIO_COMPLEMENTO;
DROP TABLE USUARIO_NOTIFICACAO;
DROP TABLE USUARIO_AUTORIZADOR;
DROP TABLE USUARIO_TROCA_SENHA_HISTORICO;
DROP TABLE SESSAO;
DROP TABLE TRACE;
DROP TABLE VARIAVEL;
DROP TABLE MENSAGEM;
DROP TABLE TIPO_EMPREENDIMENTO;
DROP TABLE PLANOS;
DROP TABLE CIDADE;
DROP TABLE UF;
DROP TABLE CAMPANHA;
DROP TABLE CARTAO;
DROP TABLE USUARIO;

SET FOREIGN_KEY_CHECKS=1;
