

-- Atualização estrutural de tabelas e campos
ALTER TABLE `CAMPANHA` MODIFY COLUMN `CAMP_DT_TERMINO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Data de término';

ALTER TABLE `CAMPANHA` ADD COLUMN `CAMP_IN_PERM_MOVER_CART` VARCHAR(1) NOT NULL DEFAULT 'S' COMMENT 'Permite mover cartão outro usuário';
